general {
}

background {
	monitor = 
	path = $HOME/.config/hypr/wallpaper1.jpg
	color = rgba(0, 0, 0, 1.0)
	blur_passes = 0
}

image {
    monitor =
    path = /home/$USER/.face # or /home/$USER/.face.icon
    size = 100
    border_size = 2
    position = 0, 170
    valign = center
    halign = bottom
}

label {
	monitor = 
	text = cmd[update:3600] echo "$USER"

	font_family = SF Pro Semibold
	font_size = 14

	position = 0, 155
	halign = center
	valign = bottom
}

input-field {
	monitor = 
	size = 200, 40
	outline_thickness = 0
	inner_color = rgba(0, 0, 0, 0.5)

	rounding = 18

	check_color = green
	fail_color = red

	font_family = SF Pro Semibold
	placeholder_text = Enter Password

	font_color = rgba(255, 255, 255, 0.6)
	fade_on_empty = false

	blur_passes = 3
	 
	position = 0, 100
	halign = center
	valign = bottom
}

label {
	monitor = 
	text = cmd[update:1000] echo "$(date +%H:%M)"

	font_family = SF Pro Bold
	font_size = 60

	color = rgba(255, 255, 255, 0.8)

	position = 0, -100
	halign = center
	valign = top
}

label {
	monitor = 
	text = cmd[update:3600] echo "$(date +%A,\ %B\ %d)"

	font_family = SF Pro Semibold
	font_size = 14

	position = 0, -80
	halign = center
	valign = top
}
